shiny:
  image:
    repository: srisehdf/test-shiny
    tag: "latest"
    pullPolicy: Always
  ingress:
    enabled: true
    hostname: test-shiny-srise.lab.sspcloud.fr
  s3:
    enabled: false
  postgresql:
    enabled: false
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
